In [72]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from mpl_toolkits.mplot3d import Axes3D

In [74]:
x = np.linspace(0, 2, 10)
y = x**2

In [76]:
y

array([0.        , 0.04938272, 0.19753086, 0.44444444, 0.79012346,
       1.2345679 , 1.77777778, 2.41975309, 3.16049383, 4.        ])

In [78]:
x

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [80]:
# Tracer un simple graphique

plt.plot(x, y)
plt.show()

In [82]:
# Tracer un nuage de points

plt.scatter(x, y)
plt.show()

In [84]:
# Les parametres
# c = 'couleur de la courbes'
# lw = 'Epaisseur de la courbes'
# ls = 'style de la courbes'

plt.plot(x, y, c = 'red', lw = 5, ls = '--')
plt.show()

In [86]:
# Cycle de vie d'une figure

plt.figure(figsize = (12, 8))
plt.plot(x, y, c = 'red', lw = 5, ls = '--', label = 'AAaH')
plt.plot(x, x*3-y, c = 'black', lw = 2, ls = '-', label = 'oKAI')
plt.title('Figure one')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()
plt.savefig('fig.png')

In [88]:
# Plusieurs graphiques sur une meme figure

plt.subplot(2, 3, 1) # 2 ligne et 3 colonnes, on est sur le graphe 1
plt.plot(x, x**2, c = 'red')

plt.subplot(2, 3, 2) # 2 ligne et 3 colonnes, on est sur le graphe 2
plt.plot(x, x**3, c = 'yellow')

plt.subplot(2, 3, 3) # 2 ligne et 3 colonnes, on est sur le graphe 3
plt.plot(x, (x//2)*x, c = 'black')

plt.subplot(2, 3, 4) # 2 ligne et 3 colonnes, on est sur le graphe 4
plt.plot(x, 3*x - 2, c = 'blue')

plt.subplot(2, 3, 5) # 2 ligne et 3 colonnes, on est sur le graphe 5
plt.plot(x, x*3+144, c = 'green')

plt.subplot(2, 3, 6) # 2 ligne et 3 colonnes, on est sur le graphe 6
plt.plot(x, (x//2)*x-21/x, c = 'gray')

/tmp/ipykernel_50999/3885204452.py:19: RuntimeWarning: divide by zero encountered in divide
  plt.plot(x, (x//2)*x-21/x, c = 'gray')


## Graphiques les plus utiles de matplotlib

### 5 - scatter (Classification)

In [92]:
iris = load_iris()
x = iris.data
y = iris.target
names = list(iris.target_names)

In [94]:
x.shape

(150, 4)

In [96]:
y.shape

(150,)

In [98]:
plt.scatter(x[:,0], x[:, 1], c = y, alpha = 0.5, s = 25) # alpha pour la transparence des points et s pour la taille
plt.xlabel('Longeur sepal')
plt.ylabel('largeur sepal')

Text(0, 0.5, 'largeur sepal')

### 4 - Graphique 3D

In [101]:
# Creer un objet axes 
ax = plt.axes(projection = '3d')
ax.scatter(x[:,0], x[:, 1], x[:, 2], c = y)

## 3 - Histogramme

In [114]:
plt.hist(x[:, 0], bins = 30) # bins nombre de sections dans l'histogramme

(array([ 4.,  1.,  4.,  2.,  5., 16.,  9.,  4.,  1.,  6., 13.,  8.,  7.,
         3.,  6., 10.,  9.,  7.,  5.,  2., 11.,  4.,  1.,  1.,  4.,  1.,
         0.,  1.,  4.,  1.]),
 array([4.3 , 4.42, 4.54, 4.66, 4.78, 4.9 , 5.02, 5.14, 5.26, 5.38, 5.5 ,
        5.62, 5.74, 5.86, 5.98, 6.1 , 6.22, 6.34, 6.46, 6.58, 6.7 , 6.82,
        6.94, 7.06, 7.18, 7.3 , 7.42, 7.54, 7.66, 7.78, 7.9 ]),
 <BarContainer object of 30 artists>)

In [125]:
# Histogramme 2D
plt.hist2d(x[:,0], x[:, 1], cmap = 'Blues') # cmap pour la couleur
plt.xlabel('Longueur sepal')
plt.ylabel('Largeur de sepal')
plt.colorbar()

In [127]:
# Histogramme d'une image

from scipy import misc
face = misc.face(gray = True)
plt.imshow(face, cmap = 'gray')

/tmp/ipykernel_50999/3735978437.py:4: DeprecationWarning: scipy.misc.face has been deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. Dataset methods have moved into the scipy.datasets module. Use scipy.datasets.face instead.
  face = misc.face(gray = True)


In [129]:
plt.hist(face.ravel(), bins = 255)

(array([2.900e+01, 6.600e+01, 5.700e+01, 1.300e+02, 3.920e+02, 8.390e+02,
        1.841e+03, 2.727e+03, 2.963e+03, 2.453e+03, 1.944e+03, 1.955e+03,
        2.176e+03, 2.567e+03, 2.775e+03, 3.073e+03, 2.973e+03, 3.565e+03,
        3.408e+03, 3.663e+03, 3.491e+03, 3.339e+03, 3.201e+03, 3.188e+03,
        3.071e+03, 3.127e+03, 2.945e+03, 2.709e+03, 2.690e+03, 2.509e+03,
        2.444e+03, 2.388e+03, 2.420e+03, 2.356e+03, 2.405e+03, 2.325e+03,
        2.458e+03, 2.330e+03, 2.348e+03, 2.314e+03, 2.341e+03, 2.455e+03,
        2.257e+03, 2.310e+03, 2.335e+03, 2.397e+03, 2.486e+03, 2.445e+03,
        2.497e+03, 2.459e+03, 0.000e+00, 2.653e+03, 2.617e+03, 2.731e+03,
        2.767e+03, 2.904e+03, 2.854e+03, 3.099e+03, 3.209e+03, 3.189e+03,
        3.358e+03, 3.396e+03, 3.458e+03, 3.460e+03, 3.589e+03, 3.768e+03,
        3.742e+03, 3.637e+03, 3.585e+03, 3.639e+03, 3.782e+03, 3.656e+03,
        3.717e+03, 3.783e+03, 3.773e+03, 3.801e+03, 3.880e+03, 3.790e+03,
        3.859e+03, 3.947e+03, 3.889e+0

## 2 - Contour plot

In [133]:
# Utilisé pour les problemes d'optimisation

## 1 - imshow

In [138]:
# Utilisé pour reprensenter un tablea

In [146]:
# Matrice de correlation d'iris
plt.imshow(np.corrcoef(x.T), cmap = 'Blues') # La transposée parceque on veut les correlations entre les colonnes et non lignes
plt.colorbar()