In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import SGDClassifier
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator

# SimpleImputer
Remplace toutes les valeurs manquantes par une valeur statistique

In [8]:
X = np.array([
    [12,5],
    [np.nan, 8],
    [14, 7],
    [1, 4]
])

In [18]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit_transform(X)

array([[12.,  5.],
       [ 9.,  8.],
       [14.,  7.],
       [ 1.,  4.]])

# KNNImputer
Remplace les valeurs manquantes par la valeur des plus proche voisins

In [25]:
imputer = KNNImputer(missing_values = np.nan, n_neighbors = 1)
imputer.fit_transform(X)

array([[12.,  5.],
       [14.,  8.],
       [14.,  7.],
       [ 1.,  4.]])

# MissngIndicator
Variable booleene qui indique l'absence de valeur dans le dataset

In [30]:
imputer = MissingIndicator(missing_values = np.nan)
imputer.fit_transform(X)

array([[False],
       [ True],
       [False],
       [False]])